const API_URL = "https//app.violet.co";

const AUTHORIZE_ENDPOINT = "api/authz/authorize";

const ENROL_ENDPOINT = "api/authz/authorize-no-eat";

const ETHEREUM_NAMESPACE = "eip155";

const VIOLET_AUTHORIZATION_CHANNEL = "VIOLET_AUTHORIZATION_CHANNEL";

export {
  API_URL,
  AUTHORIZE_ENDPOINT,
  ENROL_ENDPOINT,
  ETHEREUM_NAMESPACE,
  VIOLET_AUTHORIZATION_CHANNEL,
};
